/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiStatusAppVersion {
    /// Internal use - Minimum application version required to correctly connect and process data.
    #[serde(rename = "min_app_version")]
    pub min_app_version: i32,
    /// Internal use - Latest application version available.
    #[serde(rename = "latest_app_version")]
    pub latest_app_version: i32,
}

impl ApiStatusAppVersion {
    pub fn new(min_app_version: i32, latest_app_version: i32) -> ApiStatusAppVersion {
        ApiStatusAppVersion {
            min_app_version,
            latest_app_version,
        }
    }
}
