/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// AwardRecipient : An `Award_Recipient` object represents the team and/or person who received an award at an event.
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AwardRecipient {
    /// The TBA team key for the team that was given the award. May be null.
    #[serde(rename = "team_key", skip_serializing_if = "Option::is_none")]
    pub team_key: Option<String>,
    /// The name of the individual given the award. May be null.
    #[serde(rename = "awardee", skip_serializing_if = "Option::is_none")]
    pub awardee: Option<String>,
}

impl AwardRecipient {
    /// An `Award_Recipient` object represents the team and/or person who received an award at an event.
    pub fn new() -> AwardRecipient {
        AwardRecipient {
            team_key: None,
            awardee: None,
        }
    }
}
