/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// EliminationAllianceBackup : Backup team called in, may be null.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EliminationAllianceBackup {
    /// Team key that was called in as the backup.
    #[serde(rename = "in", skip_serializing_if = "Option::is_none")]
    pub _in: Option<String>,
    /// Team key that was replaced by the backup team.
    #[serde(rename = "out", skip_serializing_if = "Option::is_none")]
    pub out: Option<String>,
}

impl EliminationAllianceBackup {
    /// Backup team called in, may be null.
    pub fn new() -> EliminationAllianceBackup {
        EliminationAllianceBackup {
            _in: None,
            out: None,
        }
    }
}
