/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EliminationAllianceStatus {
    #[serde(rename = "playoff_average", skip_serializing_if = "Option::is_none")]
    pub playoff_average: Option<f64>,
    #[serde(rename = "level", skip_serializing_if = "Option::is_none")]
    pub level: Option<String>,
    #[serde(rename = "record", skip_serializing_if = "Option::is_none")]
    pub record: Option<crate::models::WltRecord>,
    #[serde(
        rename = "current_level_record",
        skip_serializing_if = "Option::is_none"
    )]
    pub current_level_record: Option<crate::models::WltRecord>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

impl EliminationAllianceStatus {
    pub fn new() -> EliminationAllianceStatus {
        EliminationAllianceStatus {
            playoff_average: None,
            level: None,
            record: None,
            current_level_record: None,
            status: None,
        }
    }
}
