/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventDistrictPointsTiebreakers {
    #[serde(
        rename = "highest_qual_scores",
        skip_serializing_if = "Option::is_none"
    )]
    pub highest_qual_scores: Option<Vec<i32>>,
    #[serde(rename = "qual_wins", skip_serializing_if = "Option::is_none")]
    pub qual_wins: Option<i32>,
}

impl EventDistrictPointsTiebreakers {
    pub fn new() -> EventDistrictPointsTiebreakers {
        EventDistrictPointsTiebreakers {
            highest_qual_scores: None,
            qual_wins: None,
        }
    }
}
