/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventRankingRankings {
    /// Number of matches played by this team.
    #[serde(rename = "matches_played")]
    pub matches_played: i32,
    /// The average match score during qualifications. Year specific. May be null if not relevant for a given year.
    #[serde(rename = "qual_average", skip_serializing_if = "Option::is_none")]
    pub qual_average: Option<i32>,
    /// Additional special data on the team's performance calculated by TBA.
    #[serde(rename = "extra_stats", skip_serializing_if = "Option::is_none")]
    pub extra_stats: Option<Vec<f32>>,
    /// Additional year-specific information, may be null. See parent `sort_order_info` for details.
    #[serde(rename = "sort_orders", skip_serializing_if = "Option::is_none")]
    pub sort_orders: Option<Vec<f32>>,
    #[serde(rename = "record")]
    pub record: crate::models::WltRecord,
    /// The team's rank at the event as provided by FIRST.
    #[serde(rename = "rank")]
    pub rank: i32,
    /// Number of times disqualified.
    #[serde(rename = "dq")]
    pub dq: i32,
    /// The team with this rank.
    #[serde(rename = "team_key")]
    pub team_key: String,
}

impl EventRankingRankings {
    pub fn new(
        matches_played: i32,
        record: crate::models::WltRecord,
        rank: i32,
        dq: i32,
        team_key: String,
    ) -> EventRankingRankings {
        EventRankingRankings {
            matches_played,
            qual_average: None,
            extra_stats: None,
            sort_orders: None,
            record,
            rank,
            dq,
            team_key,
        }
    }
}
