/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventRankingSortOrderInfo {
    /// Integer expressing the number of digits of precision in the number provided in `sort_orders`.
    #[serde(rename = "precision")]
    pub precision: i32,
    /// Name of the field used in the `sort_order` array.
    #[serde(rename = "name")]
    pub name: String,
}

impl EventRankingSortOrderInfo {
    pub fn new(precision: i32, name: String) -> EventRankingSortOrderInfo {
        EventRankingSortOrderInfo { precision, name }
    }
}
