/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// EventInsights : A year-specific event insight object expressed as a JSON string, separated in to `qual` and `playoff` fields. See also Event_Insights_2016, Event_Insights_2017, etc.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventInsights {
    /// Inights for the qualification round of an event
    #[serde(rename = "qual", skip_serializing_if = "Option::is_none")]
    pub qual: Option<serde_json::Value>,
    /// Insights for the playoff round of an event
    #[serde(rename = "playoff", skip_serializing_if = "Option::is_none")]
    pub playoff: Option<serde_json::Value>,
}

impl EventInsights {
    /// A year-specific event insight object expressed as a JSON string, separated in to `qual` and `playoff` fields. See also Event_Insights_2016, Event_Insights_2017, etc.
    pub fn new() -> EventInsights {
        EventInsights {
            qual: None,
            playoff: None,
        }
    }
}
