/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// MatchScoreBreakdown2018 : See the 2018 FMS API documentation for a description of each value. https://frcevents2.docs.apiary.io/#/reference/match-results/score-details

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchScoreBreakdown2018 {
    #[serde(rename = "blue", skip_serializing_if = "Option::is_none")]
    pub blue: Option<crate::models::MatchScoreBreakdown2018Alliance>,
    #[serde(rename = "red", skip_serializing_if = "Option::is_none")]
    pub red: Option<crate::models::MatchScoreBreakdown2018Alliance>,
}

impl MatchScoreBreakdown2018 {
    /// See the 2018 FMS API documentation for a description of each value. https://frcevents2.docs.apiary.io/#/reference/match-results/score-details
    pub fn new() -> MatchScoreBreakdown2018 {
        MatchScoreBreakdown2018 {
            blue: None,
            red: None,
        }
    }
}
