/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// MatchScoreBreakdown2015 : See the 2015 FMS API documentation for a description of each value

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchScoreBreakdown2015 {
    #[serde(rename = "blue", skip_serializing_if = "Option::is_none")]
    pub blue: Option<crate::models::MatchScoreBreakdown2015Alliance>,
    #[serde(rename = "red", skip_serializing_if = "Option::is_none")]
    pub red: Option<crate::models::MatchScoreBreakdown2015Alliance>,
    #[serde(rename = "coopertition", skip_serializing_if = "Option::is_none")]
    pub coopertition: Option<Coopertition>,
    #[serde(
        rename = "coopertition_points",
        skip_serializing_if = "Option::is_none"
    )]
    pub coopertition_points: Option<i32>,
}

impl MatchScoreBreakdown2015 {
    /// See the 2015 FMS API documentation for a description of each value
    pub fn new() -> MatchScoreBreakdown2015 {
        MatchScoreBreakdown2015 {
            blue: None,
            red: None,
            coopertition: None,
            coopertition_points: None,
        }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Coopertition {
    #[serde(rename = "None")]
    None,
    #[serde(rename = "Unknown")]
    Unknown,
    #[serde(rename = "Stack")]
    Stack,
}
