/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamEventStatusRankRanking {
    /// Number of matches played.
    #[serde(rename = "matches_played", skip_serializing_if = "Option::is_none")]
    pub matches_played: Option<i32>,
    /// For some years, average qualification score. Can be null.
    #[serde(rename = "qual_average", skip_serializing_if = "Option::is_none")]
    pub qual_average: Option<f64>,
    /// Ordered list of values used to determine the rank. See the `sort_order_info` property for the name of each value.
    #[serde(rename = "sort_orders", skip_serializing_if = "Option::is_none")]
    pub sort_orders: Option<Vec<f32>>,
    #[serde(rename = "record", skip_serializing_if = "Option::is_none")]
    pub record: Option<crate::models::WltRecord>,
    /// Relative rank of this team.
    #[serde(rename = "rank", skip_serializing_if = "Option::is_none")]
    pub rank: Option<i32>,
    /// Number of matches the team was disqualified for.
    #[serde(rename = "dq", skip_serializing_if = "Option::is_none")]
    pub dq: Option<i32>,
    /// TBA team key for this rank.
    #[serde(rename = "team_key", skip_serializing_if = "Option::is_none")]
    pub team_key: Option<String>,
}

impl TeamEventStatusRankRanking {
    pub fn new() -> TeamEventStatusRankRanking {
        TeamEventStatusRankRanking {
            matches_played: None,
            qual_average: None,
            sort_orders: None,
            record: None,
            rank: None,
            dq: None,
            team_key: None,
        }
    }
}
