/*
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamEventStatusRank {
    /// Number of teams ranked.
    #[serde(rename = "num_teams", skip_serializing_if = "Option::is_none")]
    pub num_teams: Option<i32>,
    #[serde(rename = "ranking", skip_serializing_if = "Option::is_none")]
    pub ranking: Option<crate::models::TeamEventStatusRankRanking>,
    /// Ordered list of names corresponding to the elements of the `sort_orders` array.
    #[serde(rename = "sort_order_info", skip_serializing_if = "Option::is_none")]
    pub sort_order_info: Option<Vec<crate::models::TeamEventStatusRankSortOrderInfo>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

impl TeamEventStatusRank {
    pub fn new() -> TeamEventStatusRank {
        TeamEventStatusRank {
            num_teams: None,
            ranking: None,
            sort_order_info: None,
            status: None,
        }
    }
}
